language: php
php:
  - 5.6

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - composer self-update
    - composer install

script:
    - php vendor/bin/codecept run -c projects/MyTests functional FirstTestCest:tryToTest --steps
